/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.parser.iengine.crf;

public class CRFExportJNI {
  public final static native void InitWorkSpace(String jarg1);
  public final static native String Parser(String jarg1);
  public final static native void TrainAll();
  public final static native void Train(String jarg1);
  public final static native String ParserBy(String jarg1, String jarg2);
}
