/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.parser.iengine.crf;

public class CRFExport {
  public static void InitWorkSpace(String pWorkPath) {
    CRFExportJNI.InitWorkSpace(pWorkPath);
  }

  public static String Parser(String pSrc) {
    return CRFExportJNI.Parser(pSrc);
  }

  public static void TrainAll() {
    CRFExportJNI.TrainAll();
  }

  public static void Train(String pName) {
    CRFExportJNI.Train(pName);
  }

  public static String ParserBy(String pSrc, String pModel) {
    return CRFExportJNI.ParserBy(pSrc, pModel);
  }

}
