#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <wakeup>;
!slot <head>;
!slot <Device>;
!slot <Action>;
!slot <Room>;
!slot <Model>;
!slot <music>;
!slot <musicaction>;
!start <callstart>;
<callstart>:<wakeup>|<Action>|<Room>|<Model>|<Device>|<dial1>|<dial2>|<dial3>|<dial4>|<dial5>|<dial6>;
<dial1>:[<head>][<wakeup>]<Action><Room><Device>;
<dial2>:[<head>][<wakeup>]<Action><Device>;
<dial3>:[<head>][<wakeup>]<Action><Room><Model>;
<dial4>:[<head>]<musicaction><music>;
<dial5>:[<head>]<Action><music>;
<dial6>:[<wakeup>][<Action>]<Model>; 
<wakeup>:小智|小志|夏至|夏之|小智|小枝|下肢|小至|下至|小知|小吃|小紫;
<head>:我想|我要|我想要|帮我|替我|给我|帮|帮忙|你给我|你替我;
<Device>:顶灯|闪光灯|射灯|大灯|夜灯|水晶灯|调光灯|壁灯|灯带|筒灯|吊灯|背景灯|泛光灯|回光灯|吸顶灯|地暖|电视机|电视|空调|台灯|风扇|电风扇|彩电|水灯|窗帘|收音机|投影仪|微波炉|洗衣机|门|扫地机器人|灯;
<Action>:打开|开启|启动|开上|运行|开|关闭|关上|关掉|闭上|闭掉|停止|停掉|停|关|调亮|调暗|看;
<Room>:客厅|卧室|起居室|主卧|客卧|客卧一|客卧二|客卧三|客卧四|客卧五|次卧|书房|主卫|次卫|卫生间|厕所|洗手间|南阳台|北阳台|过道|阳台|客厅阳台|厨房|餐厅|庭院|院子|大厅|前厅|后厅|走廊|洗手台|门口;
<Model>:回家模式|离家模式|温馨模式|宴会模式|聚会模式|影视模式|全关模式|起床模式|睡眠模式|全开模式|双控客厅|下一首|上一首|换一首|很好听|很难听|不好听|循环播放|我喜欢|我讨厌;
<music>:歌曲|歌|音乐;
<musicaction>:播放|放|来首|放首|唱|来一首|唱一首|循环|暂停;